In [1]:
import pandas as pd
import ee
import geemap

In [2]:
ee.Authenticate()

True

In [3]:
ee.Initialize(project="ee-sushantniraula01")

In [5]:
df=pd.read_csv("./map_data/final_landslide_features.csv")

In [6]:
df.head()

,Geology_Nepal_ID,Geology_geo8apg_ID,date,longitude,latitude,Dist_Fault,Dist_River,Dist_Road,Bulk_Density,CEC,...,Soil_Organic_Carbon,Soil_pH,LULC,NDVI,precipitation,rainfall_30d,rainfall_7d,aspect,elevation,slope
0,023,2719,2016-08-09,88.1100,26.7903,3979.391018,788.080909,3224.770794,119.0,225.0,...,424.0,54.0,10,6554.217391,24.237547,731.139593,26.748976,187.095205,628,23.770737
1,023,2780,2016-08-09,88.1389,26.7973,3695.155471,358.510868,3977.668132,123.0,222.0,...,456.0,55.0,10,6820.695652,24.237547,731.139593,26.748976,46.979607,546,28.621957
2,005,2719,2012-10-01,88.0499,26.8016,7195.349747,1140.761762,1643.144178,115.0,209.0,...,412.0,53.0,10,6420.478261,40.867012,266.120798,19.668407,307.546101,836,39.470354
3,026,2719,2009-08-19,88.1250,26.8042,4851.520119,853.473003,5101.698420,118.0,237.0,...,431.0,55.0,10,6416.478261,32.404659,940.074533,188.810307,205.361308,997,24.974730
4,041,2719,2015-07-01,88.0839,26.8366,9564.534453,2098.670836,229.843722,103.0,243.0,...,611.0,53.0,10,6638.086957,0.000000,484.826468,176.849350,255.013903,1740,20.586612

In [7]:
# Load Nepal boundary from GADM dataset
nepal_boundary = ee.FeatureCollection("FAO/GAUL/2015/level0").filter(ee.Filter.eq('ADM0_NAME', 'Nepal'))


# Convert latitude and longitude to GEE Features
def create_feature(row):
    return ee.Feature(ee.Geometry.Point([row["longitude"], row["latitude"]]))

features = df.apply(create_feature, axis=1)
points_fc = ee.FeatureCollection(features.tolist())

points_inside_nepal = points_fc.filterBounds(nepal_boundary)

# Create a geemap interactive map
Map = geemap.Map()

# Add Nepal boundary
Map.addLayer(nepal_boundary.style(color="blue", width=2), {}, "Nepal Boundary")

# Add points to the map
Map.addLayer(points_inside_nepal.style(color="red", pointSize=5), {}, "Filtered Points")

# Display the map
Map.centerObject(nepal_boundary, 7)
Map

Map(center=[28.268224502649357, 83.97637443188768], controls=(WidgetControl(options=['position', 'transparent_…

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("landslide_probability.csv")

In [3]:
df.head()

,Dist_Fault,Dist_River,Dist_Road,Geology_Nepal_ID,Geology_geo8apg_ID,LULC,NDVI,aspect,date,elevation,...,Coarse_Fragments,Nitrogen,Sand_Content,Silt_Content,Soil_pH,TPI,TRI,SPI,TWI,landslide_probability
0,6686.508132,109.252238,1020.811671,0,0,80,3766.913043,180.000000,2024-01-01,183,...,96.0,1744.0,596.0,245.0,62.0,-2.4,7.162402,11.849448,7.946691,0.314759
1,6686.508132,109.252238,1020.811671,0,0,50,3766.913043,150.547437,2024-01-01,192,...,86.0,1633.0,592.0,261.0,60.0,3.2,7.395945,7.138686,8.549462,0.315321
2,6934.871438,357.863366,1243.439153,0,0,50,5057.086957,0.000000,2024-01-01,194,...,86.0,1633.0,592.0,261.0,60.0,2.6,4.979960,3.140428,9.391357,0.360321
3,6934.871438,357.863366,1243.439153,0,0,40,5057.086957,209.453062,2024-01-01,196,...,83.0,1620.0,585.0,236.0,59.0,2.0,2.000000,7.287444,8.570076,0.255321
4,7183.234852,606.474602,1157.026533,0,0,40,4896.695652,48.477296,2024-01-01,192,...,83.0,1620.0,585.0,236.0,59.0,-2.2,1.788854,9.376899,8.276742,0.271987

In [5]:
df=df[['latitude','longitude','landslide_probability']].astype(float)

In [6]:
df.to_csv("landslide_plot_csv.csv",index=False)

In [7]:
df.head()

    latitude  longitude  landslide_probability
0  27.691264  84.395064               0.314759
1  27.692264  84.395064               0.315321
2  27.693264  84.395064               0.360321
3  27.694264  84.395064               0.255321
4  27.695264  84.395064               0.271987